# Data: 

***Wine Quality Dataset: https://www.kaggle.com/datasets/subhajournal/wine-quality-data-combined***

In [1]:
import pandas as pd

df = pd.read_csv('WineQuality.csv')
df

,Unnamed: 0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Type
0,2732,7.4,0.170,0.29,1.4,0.047,23.0,107.0,0.99390,3.52,0.65,10.4,6,White Wine
1,2607,5.3,0.310,0.38,10.5,0.031,53.0,140.0,0.99321,3.34,0.46,11.7,6,White Wine
2,1653,4.7,0.145,0.29,1.0,0.042,35.0,90.0,0.99080,3.76,0.49,11.3,6,White Wine
3,3264,6.9,0.260,0.29,4.2,0.043,33.0,114.0,0.99020,3.16,0.31,12.5,6,White Wine
4,4931,6.4,0.450,0.07,1.1,0.030,10.0,131.0,0.99050,2.97,0.28,10.8,5,White Wine
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32480,2838,5.0,0.255,0.22,2.7,0.043,46.0,153.0,0.99238,3.75,0.76,11.3,6,White Wine
32481,6414,6.6,0.360,0.52,11.3,0.046,8.0,110.0,0.99660,3.07,0.46,9.4,5,White Wine
32482,1126,6.3,0.200,0.24,1.7,0.052,36.0,135.0,0.99374,3.80,0.66,10.8,6,White Wine
32483,2924,6.2,0.200,0.33,5.4,0.028,21.0,75.0,0.99012,3.36,0.41,13.5,7,White Wine
32484,5462,8.1,0.280,0.46,15.4,0.059,32.0,177.0,1.00040,3.27,0.58,9.0,4,White Wine

# Dropping column titled 'Unnamed: 0'

In [2]:
df = df.drop('Unnamed: 0', axis = 1)
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Type
0,7.4,0.170,0.29,1.4,0.047,23.0,107.0,0.99390,3.52,0.65,10.4,6,White Wine
1,5.3,0.310,0.38,10.5,0.031,53.0,140.0,0.99321,3.34,0.46,11.7,6,White Wine
2,4.7,0.145,0.29,1.0,0.042,35.0,90.0,0.99080,3.76,0.49,11.3,6,White Wine
3,6.9,0.260,0.29,4.2,0.043,33.0,114.0,0.99020,3.16,0.31,12.5,6,White Wine
4,6.4,0.450,0.07,1.1,0.030,10.0,131.0,0.99050,2.97,0.28,10.8,5,White Wine
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32480,5.0,0.255,0.22,2.7,0.043,46.0,153.0,0.99238,3.75,0.76,11.3,6,White Wine
32481,6.6,0.360,0.52,11.3,0.046,8.0,110.0,0.99660,3.07,0.46,9.4,5,White Wine
32482,6.3,0.200,0.24,1.7,0.052,36.0,135.0,0.99374,3.80,0.66,10.8,6,White Wine
32483,6.2,0.200,0.33,5.4,0.028,21.0,75.0,0.99012,3.36,0.41,13.5,7,White Wine
32484,8.1,0.280,0.46,15.4,0.059,32.0,177.0,1.00040,3.27,0.58,9.0,4,White Wine

# Basic Properties of the Data

## 1. Data Types

In [3]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Type                     object
dtype: object

***Type is non-numeric categorical, Quality is numeric categorical***

## 2. Unique Types of Wine

In [4]:
df['Type'].unique()

array(['White Wine', 'Red Wine'], dtype=object)

In [5]:
df['quality'].unique()

array([6, 5, 7, 4, 8, 3, 9], dtype=int64)

# Encoding Wine Types & Quality

In [6]:
df.loc[df["Type"] == "White Wine", "Type"] = 1
df.loc[df["Type"] == "Red Wine", "Type"] = 0

In [7]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Type
0,7.4,0.170,0.29,1.4,0.047,23.0,107.0,0.99390,3.52,0.65,10.4,6,1
1,5.3,0.310,0.38,10.5,0.031,53.0,140.0,0.99321,3.34,0.46,11.7,6,1
2,4.7,0.145,0.29,1.0,0.042,35.0,90.0,0.99080,3.76,0.49,11.3,6,1
3,6.9,0.260,0.29,4.2,0.043,33.0,114.0,0.99020,3.16,0.31,12.5,6,1
4,6.4,0.450,0.07,1.1,0.030,10.0,131.0,0.99050,2.97,0.28,10.8,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32480,5.0,0.255,0.22,2.7,0.043,46.0,153.0,0.99238,3.75,0.76,11.3,6,1
32481,6.6,0.360,0.52,11.3,0.046,8.0,110.0,0.99660,3.07,0.46,9.4,5,1
32482,6.3,0.200,0.24,1.7,0.052,36.0,135.0,0.99374,3.80,0.66,10.8,6,1
32483,6.2,0.200,0.33,5.4,0.028,21.0,75.0,0.99012,3.36,0.41,13.5,7,1
32484,8.1,0.280,0.46,15.4,0.059,32.0,177.0,1.00040,3.27,0.58,9.0,4,1

# Prediction: Linear Discriminant Analysis

In [8]:
from sklearn.model_selection import train_test_split

X = df.drop('quality', axis = 1)
y = df['quality']
X2 = X.copy()

In [9]:
y

0        6
1        6
2        6
3        6
4        5
        ..
32480    6
32481    5
32482    6
32483    7
32484    4
Name: quality, Length: 32485, dtype: int64

In [10]:
# Train - Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [11]:
X_train.shape

(29236, 12)

In [12]:
X_test.shape

(3249, 12)

In [13]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [14]:
lda = LinearDiscriminantAnalysis(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

In [15]:
# classify using random forest classifier
classifier = RandomForestClassifier(max_depth=25, random_state=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [16]:
# print the accuracy and confusion matrix
print('Accuracy : ' + str(accuracy_score(y_test, y_pred)))
conf_m = confusion_matrix(y_test, y_pred)
print(conf_m)

Accuracy : 0.9907663896583564
[[   8    0    0    0    0    0    0]
 [   0  106    1    2    0    0    0]
 [   1    0 1085    7    1    0    0]
 [   0    1   11 1352    0    0    0]
 [   0    0    1    3  573    0    0]
 [   0    0    0    0    2   94    0]
 [   0    0    0    0    0    0    1]]